apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
data:
  PORT: "3000"
  DB_HOST: "10.101.178.107"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DB_PORT: "5432"
  DB_NAME: "todos_db"
  DB_VERSION: "10.4"