services:
  docker:
    image: docker:dind
    container_name: jenkins-docker-gradle
    privileged: true
    restart: unless-stopped
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - docker_certs:/certs/client
      - jenkins_home:/var/jenkins_home

  jenkins:
    image: jenkins-gradle:v2
    container_name: jenkins-gradle
    restart: unless-stopped
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    volumes:
      - docker_certs:/certs/client:ro
      - jenkins_home:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000

volumes:
  docker_certs:
  jenkins_home:
